"""
pdf_parser.py
=============
Extracts native (embedded) text from PDF pages using PyMuPDF, and
determines which pages have insufficient text to be considered
"native" — those get flagged for OCR by the orchestrator.

Why this file is needed:
    This is the FAST path. Most business PDFs (invoices generated by
    software, reports exported from Word/Excel) have a real text layer,
    and pulling text directly is orders of magnitude faster and more
    accurate than OCR. We always try this first.

Which other files use this:
    document_processor.py (the orchestrator) calls this for every PDF,
    then hands off only the low-text pages to ocr_parser.py.
"""

import fitz  # PyMuPDF's import name is historical, unrelated to the package name

from app.ingestion.schemas import ExtractionMethod, ParsedPage

# Pages with fewer extracted characters than this are treated as having
# no usable text layer (i.e., they're scanned images or blank).
# This number is a heuristic, not a law of nature — we picked a small
# value deliberately conservative enough that a page with even a short
# native caption isn't wrongly sent to slower OCR.
MIN_NATIVE_TEXT_CHARS = 10


def extract_native_pages(pdf_path: str) -> list[ParsedPage]:
    """
    Opens a PDF and extracts text from every page using its embedded
    text layer (no OCR at this stage).

    Returns a ParsedPage for every page — pages with too little text
    still get a ParsedPage, but with extraction_method=NATIVE and mostly
    empty text; the orchestrator decides whether to re-process such pages
    with OCR afterward (this function's job is only extraction+detection,
    not the OCR itself, keeping this module single-responsibility).
    """
    # `fitz.open(...)` returns a Document object. Using it as a context
    # manager (`with ... as`) guarantees the underlying file handle is
    # closed even if an exception happens partway through — without
    # this, a crash on page 50 of a 100-page PDF would leak the open
    # file handle.
    pages: list[ParsedPage] = []

    with fitz.open(pdf_path) as doc:
        for page_index, page in enumerate(doc):
            # PyMuPDF pages are 0-indexed internally; we convert to the
            # 1-indexed convention humans use ("page 1", not "page 0").
            page_number = page_index + 1

            raw_text = page.get_text()  # type: ignore[attr-defined]
            stripped = raw_text.strip()

            pages.append(
                ParsedPage(
                    page_number=page_number,
                    text=raw_text,
                    extraction_method=ExtractionMethod.NATIVE,
                )
            )

    return pages


def needs_ocr(page: ParsedPage) -> bool:
    """
    Decides whether a page's native extraction was insufficient and
    should be re-processed with OCR.
    """
    return len(page.text.strip()) < MIN_NATIVE_TEXT_CHARS
